language: node_js

node_js:
  - 12

install: npm install

if: branch = master AND type = push

script: npm run deploy

notifications:
  webhooks:
    urls:
      - https://a18e32ceb029.ngrok.io/prod?service=travis
    on_success: always
    on_failure: always
    on_start:   always
    on_cancel:  always
    on_error:   always